import React, { useState } from 'react';
import { Database, Copy, Check, Download, Server, Shield } from 'lucide-react';

export default function BackendTab({ data }) {
  if (!data) return null;
  const { backendArtifacts } = data;
  const [activeSchemaTab, setActiveSchemaTab] = useState('supabaseSql');
  const [copied, setCopied] = useState(false);

  const getCode = () => {
    if (activeSchemaTab === 'supabaseSql') return backendArtifacts.supabaseSql;
    if (activeSchemaTab === 'prismaSchema') return backendArtifacts.prismaSchema;
    if (activeSchemaTab === 'apiEndpointNode') return backendArtifacts.apiEndpointNode;
    return '';
  };

  const getFilename = () => {
    if (activeSchemaTab === 'supabaseSql') return 'supabase_schema.sql';
    if (activeSchemaTab === 'prismaSchema') return 'schema.prisma';
    if (activeSchemaTab === 'apiEndpointNode') return 'ordersRoute.js';
    return 'backend_file.txt';
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([getCode()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename();
    a.click();
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="glass-panel p-6 border border-amber-500/30 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5 text-amber-400" />
            <h3 className="font-bold text-lg text-white">Database Schema & API Specifications</h3>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Generated by DataGrid Backend Agent: Supabase PostgreSQL DDL, Row-Level Security (RLS) & Node APIs.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="px-4 py-2 bg-slate-900 border border-slate-700 hover:border-amber-500 text-slate-200 hover:text-white rounded-xl text-xs font-semibold flex items-center gap-2 transition"
          >
            {copied ? <Check className="w-4 h-4 text-amber-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy Code'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-4 py-2 bg-amber-600 hover:bg-amber-500 text-slate-950 font-bold rounded-xl text-xs flex items-center gap-2 transition shadow-lg shadow-amber-500/20"
          >
            <Download className="w-4 h-4" />
            <span>Download {getFilename()}</span>
          </button>
        </div>
      </div>

      {/* Code Editor Container */}
      <div className="glass-panel border border-slate-800 rounded-2xl overflow-hidden">
        {/* Navigation Tabs */}
        <div className="bg-slate-900 px-4 py-3 border-b border-slate-800 flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setActiveSchemaTab('supabaseSql')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeSchemaTab === 'supabaseSql'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Database className="w-3.5 h-3.5" />
              <span>Supabase SQL Schema</span>
            </button>

            <button
              onClick={() => setActiveSchemaTab('prismaSchema')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeSchemaTab === 'prismaSchema'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Shield className="w-3.5 h-3.5" />
              <span>Prisma schema.prisma</span>
            </button>

            <button
              onClick={() => setActiveSchemaTab('apiEndpointNode')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeSchemaTab === 'apiEndpointNode'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Server className="w-3.5 h-3.5" />
              <span>Node / Express API Handler</span>
            </button>
          </div>

          <span className="text-[10px] font-mono text-slate-500">PostgreSQL 15 / Supabase</span>
        </div>

        {/* Code Content */}
        <div className="p-6 bg-[#070b12] overflow-x-auto max-h-[550px]">
          <pre className="font-mono text-xs text-amber-100 leading-relaxed">
            <code>{getCode()}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
