import React, { useState } from 'react';
import { Database, Copy, Check, Download, Server, Shield, Network, Key, Link } from 'lucide-react';

export default function BackendTab({ data }) {
  if (!data) return null;
  const { backendArtifacts } = data;

  const [activeViewMode, setActiveViewMode] = useState('erdDiagram'); // 'erdDiagram', 'supabaseSql', 'prismaSchema', 'apiEndpointNode'
  const [copied, setCopied] = useState(false);

  const getCode = () => {
    if (activeViewMode === 'supabaseSql') return backendArtifacts.supabaseSql;
    if (activeViewMode === 'prismaSchema') return backendArtifacts.prismaSchema;
    if (activeViewMode === 'apiEndpointNode') return backendArtifacts.apiEndpointNode;
    return '';
  };

  const getFilename = () => {
    if (activeViewMode === 'supabaseSql') return 'supabase_schema.sql';
    if (activeViewMode === 'prismaSchema') return 'schema.prisma';
    if (activeViewMode === 'apiEndpointNode') return 'ordersRoute.js';
    return 'backend_schema.sql';
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([getCode()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename();
    a.click();
  };

  // ERD Tables Visual Specification
  const erdTables = [
    {
      name: 'profiles',
      badge: 'Auth & Users',
      fields: [
        { name: 'id', type: 'UUID', isPk: true, isFk: true, fkRef: 'auth.users(id)' },
        { name: 'email', type: 'VARCHAR(255)', isUnique: true },
        { name: 'full_name', type: 'TEXT' },
        { name: 'phone_number', type: 'VARCHAR(50)' },
        { name: 'created_at', type: 'TIMESTAMP' }
      ]
    },
    {
      name: 'products',
      badge: 'Catalog Menu',
      fields: [
        { name: 'id', type: 'UUID', isPk: true },
        { name: 'title', type: 'VARCHAR(255)' },
        { name: 'slug', type: 'VARCHAR(255)', isUnique: true },
        { name: 'price', type: 'DECIMAL(10,2)' },
        { name: 'category', type: 'VARCHAR(100)' },
        { name: 'is_available', type: 'BOOLEAN' }
      ]
    },
    {
      name: 'orders',
      badge: 'Transactions',
      fields: [
        { name: 'id', type: 'UUID', isPk: true },
        { name: 'user_id', type: 'UUID', isFk: true, fkRef: 'profiles(id)' },
        { name: 'total_amount', type: 'DECIMAL(10,2)' },
        { name: 'status', type: 'VARCHAR(50)' },
        { name: 'delivery_address', type: 'TEXT' },
        { name: 'created_at', type: 'TIMESTAMP' }
      ]
    },
    {
      name: 'order_items',
      badge: 'Junction Line Items',
      fields: [
        { name: 'id', type: 'UUID', isPk: true },
        { name: 'order_id', type: 'UUID', isFk: true, fkRef: 'orders(id)' },
        { name: 'product_id', type: 'UUID', isFk: true, fkRef: 'products(id)' },
        { name: 'quantity', type: 'INTEGER' },
        { name: 'unit_price', type: 'DECIMAL(10,2)' }
      ]
    }
  ];

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="glass-panel p-6 border border-amber-500/30 flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5 text-amber-400" />
            <h3 className="font-bold text-lg text-white">Database Architecture & Visual ERD</h3>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Generated by DataGrid Agent: Supabase PostgreSQL DDL, Row-Level Security (RLS) & Node APIs.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {activeViewMode !== 'erdDiagram' && (
            <>
              <button
                onClick={handleCopy}
                className="px-4 py-2 bg-slate-900 border border-slate-700 hover:border-amber-500 text-slate-200 hover:text-white rounded-xl text-xs font-semibold flex items-center gap-2 transition"
              >
                {copied ? <Check className="w-4 h-4 text-amber-400" /> : <Copy className="w-4 h-4" />}
                <span>{copied ? 'Copied!' : 'Copy Code'}</span>
              </button>

              <button
                onClick={handleDownload}
                className="px-4 py-2 bg-amber-600 hover:bg-amber-500 text-slate-950 font-bold rounded-xl text-xs flex items-center gap-2 transition shadow-lg shadow-amber-500/20"
              >
                <Download className="w-4 h-4" />
                <span>Download {getFilename()}</span>
              </button>
            </>
          )}
        </div>
      </div>

      {/* Navigation Mode Bar */}
      <div className="glass-panel border border-slate-800 rounded-2xl overflow-hidden">
        <div className="bg-slate-900 px-4 py-3 border-b border-slate-800 flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setActiveViewMode('erdDiagram')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeViewMode === 'erdDiagram'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Network className="w-3.5 h-3.5" />
              <span>Visual ERD Diagram</span>
            </button>

            <button
              onClick={() => setActiveViewMode('supabaseSql')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeViewMode === 'supabaseSql'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Database className="w-3.5 h-3.5" />
              <span>Supabase SQL DDL</span>
            </button>

            <button
              onClick={() => setActiveViewMode('prismaSchema')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeViewMode === 'prismaSchema'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Shield className="w-3.5 h-3.5" />
              <span>Prisma Schema</span>
            </button>

            <button
              onClick={() => setActiveViewMode('apiEndpointNode')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-mono font-semibold transition flex items-center gap-1.5 ${
                activeViewMode === 'apiEndpointNode'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Server className="w-3.5 h-3.5" />
              <span>Express API Endpoint</span>
            </button>
          </div>

          <span className="text-[10px] font-mono text-slate-500">PostgreSQL 15 + RLS Security</span>
        </div>

        {/* View Mode Content */}
        {activeViewMode === 'erdDiagram' ? (
          /* VISUAL ERD CANVAS */
          <div className="p-6 bg-[#070b12] space-y-6">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3 text-xs">
              <span className="text-amber-400 font-bold">Relational Schema Diagram (4 Tables)</span>
              <span className="text-slate-500 font-mono">Row Level Security (RLS) Active</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {erdTables.map((table, idx) => (
                <div key={idx} className="glass-panel p-5 border border-slate-800 hover:border-amber-500/40 transition">
                  <div className="flex items-center justify-between mb-3 border-b border-slate-800 pb-2">
                    <div className="flex items-center gap-2">
                      <Database className="w-4 h-4 text-amber-400" />
                      <h4 className="font-mono font-bold text-sm text-white">{table.name}</h4>
                    </div>
                    <span className="text-[9px] font-semibold px-2 py-0.5 rounded bg-slate-800 text-slate-400">
                      {table.badge}
                    </span>
                  </div>

                  <div className="space-y-1.5 font-mono text-xs">
                    {table.fields.map((f, fIdx) => (
                      <div key={fIdx} className="flex items-center justify-between p-1.5 rounded bg-slate-900/60 text-slate-300">
                        <div className="flex items-center gap-2">
                          {f.isPk && <Key className="w-3 h-3 text-amber-400" />}
                          {f.isFk && <Link className="w-3 h-3 text-cyan-400" />}
                          <span className={f.isPk ? 'text-amber-300 font-bold' : ''}>{f.name}</span>
                        </div>

                        <div className="flex items-center gap-2">
                          {f.fkRef && <span className="text-[9px] text-cyan-400">→ {f.fkRef}</span>}
                          <span className="text-[10px] text-slate-500">{f.type}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : (
          /* CODE EDITOR VIEW */
          <div className="p-6 bg-[#070b12] overflow-x-auto max-h-[550px]">
            <pre className="font-mono text-xs text-amber-100 leading-relaxed">
              <code>{getCode()}</code>
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}