import React from 'react';
import { X, Download, Database, Code2, FileText, CheckCircle } from 'lucide-react';

export default function ExportModal({ isOpen, onClose, startupData }) {
  if (!isOpen || !startupData) return null;

  const downloadFile = (content, filename, type = 'text/plain;charset=utf-8') => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
  };

  const handleExportSql = () => {
    downloadFile(startupData.backendArtifacts.supabaseSql, `${startupData.branding.brandName.toLowerCase().replace(/[^a-z0-9]/g, '')}_schema.sql`);
  };

  const handleExportReact = () => {
    downloadFile(startupData.codeArtifacts.reactApp, `${startupData.branding.brandName.replace(/[^a-zA-Z0-9]/g, '')}_App.jsx`);
  };

  const handleExportMarkdown = () => {
    const md = `# ${startupData.branding.brandName} - Startup Execution Blueprint
> Generated by VentureForge AI Multi-Agent Engine on ${new Date().toLocaleDateString()}

## 🎯 Executive Summary
- **Tagline**: ${startupData.branding.tagline}
- **Market Category**: ${startupData.meta.marketCategory}
- **Estimated TAM**: ${startupData.meta.estimatedTAM}
- **Feasibility Score**: ${startupData.meta.feasibilityScore} / 100

## 🎨 Branding & Identity
- **Brand Vibe**: ${startupData.branding.brandVibe}
- **Primary Accent**: ${startupData.branding.colorPalette[0].hex}
- **Deep Secondary**: ${startupData.branding.colorPalette[1].hex}
- **AI Logo Prompt**: ${startupData.branding.logoPrompt}

## 📊 Market Validation (SWOT)
### Strengths
${startupData.validation.swot.strengths.map(s => `- ${s}`).join('\n')}

### Weaknesses
${startupData.validation.swot.weaknesses.map(w => `- ${w}`).join('\n')}

## 📣 Go-To-Market Channels
${startupData.marketing.goToMarketChannels.map(c => `- **${c.channel}**: ${c.focus}`).join('\n')}
`;
    downloadFile(md, `${startupData.branding.brandName.toLowerCase().replace(/[^a-z0-9]/g, '')}_blueprint.md`);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="glass-panel p-6 max-w-lg w-full border border-indigo-500/30 relative">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white transition"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 rounded-xl bg-gradient-to-tr from-indigo-500 to-purple-600 text-white shadow-lg shadow-indigo-500/20">
            <Download className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-bold text-xl text-white">Export Startup Launch Package</h3>
            <p className="text-xs text-slate-400">Download complete code, SQL schema & pitch docs</p>
          </div>
        </div>

        <div className="space-y-3 mb-6">
          <button
            onClick={handleExportSql}
            className="w-full p-4 rounded-xl bg-slate-900 border border-slate-800 hover:border-amber-500/50 text-left transition flex items-center justify-between group"
          >
            <div className="flex items-center gap-3">
              <Database className="w-5 h-5 text-amber-400 group-hover:scale-110 transition" />
              <div>
                <h4 className="font-bold text-sm text-white">Supabase PostgreSQL Schema</h4>
                <p className="text-xs text-slate-400">Tables, indexes, and RLS security rules (.sql)</p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-500 group-hover:text-amber-400 transition" />
          </button>

          <button
            onClick={handleExportReact}
            className="w-full p-4 rounded-xl bg-slate-900 border border-slate-800 hover:border-emerald-500/50 text-left transition flex items-center justify-between group"
          >
            <div className="flex items-center gap-3">
              <Code2 className="w-5 h-5 text-emerald-400 group-hover:scale-110 transition" />
              <div>
                <h4 className="font-bold text-sm text-white">React 18 Landing Page Code</h4>
                <p className="text-xs text-slate-400">Complete frontend component source (.jsx)</p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-500 group-hover:text-emerald-400 transition" />
          </button>

          <button
            onClick={handleExportMarkdown}
            className="w-full p-4 rounded-xl bg-slate-900 border border-slate-800 hover:border-indigo-500/50 text-left transition flex items-center justify-between group"
          >
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-indigo-400 group-hover:scale-110 transition" />
              <div>
                <h4 className="font-bold text-sm text-white">Full Business Pitch Blueprint</h4>
                <p className="text-xs text-slate-400">Branding, SWOT, TAM, and GTM strategy (.md)</p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-500 group-hover:text-indigo-400 transition" />
          </button>
        </div>

        <div className="pt-3 border-t border-slate-800 text-center">
          <button
            onClick={onClose}
            className="px-6 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold text-xs transition"
          >
            Close Window
          </button>
        </div>
      </div>
    </div>
  );
}
